name: Deploy to Staging

on:
  push:
    branches: [ staging ]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - id: filter
        name: Detect changed paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  deploy:
    needs: detect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ### -------- Build frontend --------
      - name: Setup Node (for frontend)
        if: needs.detect.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build frontend
        if: needs.detect.outputs.frontend == 'true'
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy frontend to staging
        if: needs.detect.outputs.frontend == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./frontend/dist/
          server-dir: ./staging/  # adjust based on your hosting setup

      ### -------- Deploy backend --------
      - name: Deploy backend to staging
        if: needs.detect.outputs.backend == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./backend/
          server-dir: ./staging/api/  # adjust based on your hosting setup